-
  name: 'John Smith'
  profile:
-
  name: 'User User'
  profile:
-
  name: 'Martin Hunter'
  profile:
    general_info:
      city: Miami
      state: Florida
      tagline: Testing new waters.
      zip_code: '33144'
      description: Fun, educated, intelligent but very busy schedule, so no time for
        games.
      address_line_1: 21 SW 59th Ave
      address_line_2: ''
    personal_preferences:
      sex: M
      partners_sex: F
      relationship: M
      want_relationship: D
    date_preferences:
      smoker: D
      drinker: DC
      description: Something that would surprise both people involved. I am a very busy
        man and time is go out and meet new friends is not as much as I would like.
        I am interested in a fun person that I can share some private time with.
      accepted_distance_do_care: 'false'
    optional_info:
      age: '39'
      height: '191'
      smoker: O
      address: ''
      drinker: N
      children: N
      religion: C
      body_type: Av
      education: G
      ethnicity: W
      eye_color: brown
      net_worth: ''
      hair_color: LBro
      occupation: International trade
      annual_income: ''
-
  name: 'Robert Gill'
  profile:
    general_info:
      city: Miami
      state: Florida
      tagline: Make it happen!
      zip_code: '33144'
      description: Well what can I say. I'm 28 years young, living life one day at a
        time!!! Have been living back in Miami for a few years now since graduating
        college and can't say I want to leave. I love the beach, meeting fun and interesting
        people, and enjoying all the cool little spots the city has to offer.
      address_line_1: 6456 SW 10th Terrace
      address_line_2: ''
    personal_preferences:
      sex: M
      partners_sex: F
      relationship: S
      want_relationship: D
    date_preferences:
      smoker: N
      drinker: N
      description: This is a tough one, some dates have gone really well. Some not so
        much. Definitely depends on chemistry! Other than that I would say the perfect
        date would be a mix between a nice dinner somewhere (preferably somewhere outdoors
        or by the water) and a night out with some music in the background and upbeat
        vibe (Say the shoreclub on a Friday).
      accepted_distance_do_care: 'false'
    optional_info:
      age: '29'
      height: '168'
      smoker: N
      address: ''
      drinker: N
      children: N
      religion: J
      body_type: At
      education: G
      ethnicity: L
      eye_color: other
      net_worth: ''
      hair_color: DBro
      occupation: Investment Banking
      annual_income: '120000'
-
  name: 'Sophia Morgan'
  profile:
    general_info:
      city: Miami
      state: Florida
      tagline: Glass Half Full..
      zip_code: '33155'
      description: Here is a brief description of myself...mature,smart,sexy, cerebral,
        passionate, loyal, caring, trustworthy,understanding young lady. I have had
        a variety of life experiences and I like to live life to the fullest! I am not
        a conventional person and I don't like to be placed in a box. I have always
        been a more progressive thinker but I was placed in this world ahead of my time.
        I have a very youthful appearance and although I will be flirty forty this year
        I am often told by people that have nothing to gain that I look like I am in
        my late twenties. I'll take that (smile) how about you?
      address_line_1: 5920 SW 16th St
      address_line_2: ''
    personal_preferences:
      sex: F
      partners_sex: M
      relationship: D
      want_relationship: D
    date_preferences:
      smoker: D
      drinker: DC
      description: My ideal first date consists of inviting company, delectable food
        and an amazing atmosphere. Sexy music ( think Beres Hammond, Greggory Issac)
        and tropical drinks are a very welcome bonus (well maybe that should be the
        second date) ha-ha. I want to feel like the lady that I am. I love a gentleman
        (opening car doors, pulling out my chair);however, if that isn't your thing
        I will be a soldier and open my own door (I may not agree to a second date)
        :) Even though I am a forward thinker I like to indulge my sense of femininity
        in this ambiguous world of political correctness when interacting with the opposite
        sex (smile). In other words, by all means treat me like a lady. I am not looking
        for payment for the first date (or any date for that matter). I just want to
        show up,look beautiful,engage you in stimulating conversation, and have a great
        time (and not pay for or go dutch for dinner...old school). If we click and
        you decide to spoil me madly I will not object (smile).
      accepted_distance: '50'
      accepted_distance_do_care: 'true'
    optional_info:
      age: '39'
      height: '163'
      smoker: N
      address: ''
      drinker: N
      children: N
      religion: C
      body_type: Av
      education: S
      ethnicity: O
      eye_color: brown
      net_worth: ''
      hair_color: DBro
      occupation: Transportation
      annual_income: ''
-
  name: 'Mia Mitchell'
  profile:
    general_info:
      city: Miami
      state: Florida
      tagline: «Beauty comes from within»
      zip_code: '33144'
      description: "I like to enjoy all the good things in life and I'm not just talking
        about traveling, dining, or shopping. I love to laugh, joke around, and bring
        a smile to those around me, especially my loved ones. I'm a big believer that
        it doesn't matter where I am or what I'm doing as long as I have that genuine
        smile on my face that’s all that really matters.\r\n\r\nI love to practice aerobics
        such as: Zumba, Power Sculpt, and Cardio Kickboxing. I also enjoy Cooking, Dining
        out, Movies/Videos, Exploring new areas, going to the beach, Travel/Sightseeing,
        Volunteering, and Wine tasting.\r\n"
      address_line_1: 940 Sylvania Blvd
      address_line_2: ''
    personal_preferences:
      sex: F
      partners_sex: M
      relationship: D
      want_relationship: D
    date_preferences:
      smoker: N
      drinker: N
      description: I'm not picky as long as we are able to have some time to talk and
        connect with each other.
      accepted_distance_do_care: 'false'
    optional_info:
      age: '25'
      height: '173'
      smoker: N
      address: ''
      drinker: N
      children: C1
      religion: C
      body_type: At
      education: S
      ethnicity: L
      eye_color: brown
      net_worth: ''
      hair_color: DBro
      occupation: Sales
      annual_income: ''

