empty: '-'
sex:
  empty: 
  items:
    - M: Male
    - F: Female
relationship:
  empty: 
  items:
    - S: Single
    - D: Divorced
    - W: Widowed
    - M: Married
    - Se: Separated
    - Da: Dating
    - C: Cohabiting
want_relationship:
  empty: 
  items:
    - S: Short Term Relationship
    - D: Date
    - F: Friendship
    - A: Activity Partner
smoker:
  empty: Smoking habits?
  items:
    - S: Smoker
    - N: Non-smoker
    - O: Occasional smoker
    - D: Don't care
me_smoker:
  empty: Smoking habits?
  items:
    - S: Smoker
    - N: Non-smoker
    - O: Occasional smoker
drinker:
  empty: Drinking habits?
  items:
    - D: Drink every night
    - N: Occasionally
    - ND: Non-drinker
    - DC: Don't care
me_drinker:
  empty: Drinking habits?
  items:
    - D: Drink every night
    - N: Occasionally
    - ND: Non-drinker
education:
  empty: Select education please
  items:
    - H: High School
    - S: Some College
    - A: Associates Degree
    - B: Bachelors Degree
    - G: Graduate Degree
    - P: Post Doctoral
body_type:
  empty: Select body type please
  items:
    - S: Slim / Slender
    - At: Athletic
    - Av: Average
    - E: A Few Extra Pounds
    - F: Full / Overweight
religion:
  empty: Select religion please
  items:
    - A: Agnostic
    - B: Buddhist
    - C: Christian
    - H: Hindu
    - J: Jewish
    - M: Muslim
    - O: Other Religion
ethnicity:
  empty: Select ethnicity please
  items:
    - A: Asian
    - B: Black / African Descent
    - L: Latin / Hispanic
    - E: East Indian
    - M: Middle Eastern
    - MR: Mixed Race
    - N: Native American
    - P: Pacific Islander
    - W: White / Caucasian
    - O: Other Ethnicity
eye_color:
  empty: Select eye color please
  items:
    - black: Black Eyes
    - blue: Blue Eyes
    - brown: Brown Eyes
    - gray: Gray Eyes
    - green: Green Eyes
    - other: Other Eyes
hair_color:
  empty: Select hair color please
  items:
    - A: Auburn Hair
    - Bla: Black Hair
    - Blo: Blonde Hair
    - DBlo: Dark Blonde Hair
    - LBro: Light Brown Hair
    - DBro: Dark Brown Hair
    - G: Gray Hair
    - R: Red Hair
    - W: White Hair
    - O: Other Hair
children:
  empty: Select children please
  items:
    - N: No Children
    - C1: 1 Child
    - C2: 2 Children
    - C3: 3 Child
    - More: '> 3 Children'
height:
  empty: Select height please
  items:
    - SS: '< 140 cm'
    - S4: '140 - 150 cm'
    - S5: '150 - 160 cm'
    - S6: '160 - 165 cm'
    - M65: '165 - 170 cm'
    - M7: '170 - 175 cm'
    - M75: '175 - 180 cm'
    - L8: '180 - 185 cm'
    - L85: '185 - 190 cm'
    - L9: '190 - 195 cm'
    - L95: '195 - 200 cm'
    - LL: '> 200 cm'
income:
  empty: Select your yearly income please
  items:
    - N: '< 10,000 $ per year'
    - S: '10,000 - 30,000 $ per year'
    - M: '30,000 - 50,000 $ per year'
    - M1: '50,000 - 70,000 $ per year'
    - M2: '70,000 - 100,000 $ per year'
    - M3: '100,000 - 150,000 $ per year'
    - H: '150,000 - 500,000 $ per year'
    - HH: "Ok, I'm VERY wealthy"
net_worth:
  empty: Select your net worth please
  items:
    - N: '< 50,000 $'
    - S: '50,000 - 150,000 $'
    - M: '150,000 - 250,000 $'
    - M1: '250,000 - 350,000 $'
    - M2: '350,000 - 500,000 $'
    - M3: '500,000 - 1,500,000 $'
    - H: '1,500,000 - 5,000,000 $'
    - HH: "Ok, I'm VERY wealthy"

