common:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] || '' %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] || '' %>
  s3_bucket: 'payperdate'
  airbrake_api_key: <%= ENV['AIRBRAKE_API_KEY'] %>
  google_analytics_value: <%= ENV['GA_VALUE'] || '' %>
  url_with_port: http://localhost:3000
  host: localhost:3000

  recaptcha:
    public_key: 6LfoU-MSAAAAAJkcGfgpMtKBuGuh41oGizqW8ksW
    private_key: 6LfoU-MSAAAAAAbA6Wua96F8PSbZnoiLz-DcLrT_

  facebook:
    app_id: 187477277963833
    app_secret: 18e0f6e229a06b15a2c047c990f44dc5

  twitter:
    app_id: MSn1xUVKKSEyLpLcSQoGBQ
    app_secret: Zl9folFaGWHKep6cV6ouD1MJ0uCMBNOjpeqXNmPuPM

  mailer:
    delivery_method: :smtp
    smtp_settings:
      user_name: 'payperdate-e2628fe3aea4a5d8'
      password:  '7a0189049f61178d'
      address: mailtrap.io
      port: 2525
      authentication: :plain

  twilio:
    account_sid: AC3ba3aa95e96484be85de0a54d158c8c1
    auth_token: 3b18fea775dbad1720212f11fffe53ab
    sms_application_sid: AP4ac1d80b640a005a81d660d59d2bed13
    from: '+15005550006'

test:
  s3_bucket: 'playjoiner-development'

  #NOTE: I need setup Sandbox API keys to do not spend real money in tests.
  twilio:
    account_sid: AC3ba3aa95e96484be85de0a54d158c8c1
    auth_token: 3b18fea775dbad1720212f11fffe53ab
    sms_application_sid: AP4ac1d80b640a005a81d660d59d2bed13
    from: '+15005550006'

staging:
  s3_bucket: 'payperdate-staging'
  url_with_port: http://payperdate-staging.herokuapp.com
  host: payperdate-staging.herokuapp.com
  mailer:
    delivery_method: :smtp
    smtp_settings:
      user_name: 'payperdate-e2628fe3aea4a5d8'
      password:  '7a0189049f61178d'
      address: mailtrap.io
      port: 2525
      authentication: :plain

  facebook:
    app_id: 465140673576329
    app_secret: bf6cf7f765d938dd09a8ee4b69146005

production:
  s3_bucket: 'payperdate-production'
  url_with_port: http://payperdate-staging.herokuapp.com
  host: payperdate-staging.herokuapp.com/
  mailer:
    delivery_method: :smtp
