common:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] || '' %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] || '' %>
  s3_bucket: 'payperdate'
  airbrake_api_key: <%= ENV['AIRBRAKE_API_KEY'] %>
  google_analytics_value: <%= ENV['GA_VALUE'] || '' %>
  url_with_port: http://localhost:3000
  host: localhost:3000

  recaptcha:
    public_key: 6LfoU-MSAAAAAJkcGfgpMtKBuGuh41oGizqW8ksW
    private_key: 6LfoU-MSAAAAAAbA6Wua96F8PSbZnoiLz-DcLrT_

  facebook:
    app_id: 187477277963833
    app_secret: 18e0f6e229a06b15a2c047c990f44dc5

  twitter:
    app_id: MSn1xUVKKSEyLpLcSQoGBQ
    app_secret: Zl9folFaGWHKep6cV6ouD1MJ0uCMBNOjpeqXNmPuPM

  mailer:
    delivery_method: :test
    smtp_settings:
      user_name: 'payperdate-staging'
      password:  '90e60916630bd963'
      address: mailtrap.io
      port: 2525
      authentication: :plain

test:

staging:
  s3_bucket: 'payperdate-staging'
  url_with_port: http://payperdate-staging.herokuapp.com
  host: payperdate-staging.herokuapp.com
  mailer:
    delivery_method: :smtp

  facebook:
    app_id: 465140673576329
    app_secret: bf6cf7f765d938dd09a8ee4b69146005

  twitter:
    app_id: 5Xu4GAOxQDZ8RxzvsYYtHw
    app_secret: Cadb937Wg1wmHMYeI3SehUSb1ixmqRVG3JEXN221Qk

production:
  s3_bucket: 'payperdate-production'
  url_with_port: http://payperdate-staging.herokuapp.com
  host: payperdate-staging.herokuapp.com/
  mailer:
    delivery_method: :smtp
